### ISSUE TITLE
Different_Result_when_using_nn.DataParallelTable(1, true)

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [kenshohara/video-classification-3d-cnn#1]
Thanks for the nice works! @kenshohara 
I met a problem when i run your provided code,
when i using  nn.DataParallelTable(1, true) there, the result is differert when using the nn.DataParallelTable(1, false) Others are all same.
Could you please tell me why? and which one is right?
Thank you very much!

**Comment by kenshohara** [comment]
This is the explanation about DataParallelTable.
https://github.com/torch/cunn/blob/master/doc/cunnmodules.md

When I trained the models, I used ```nn.DataParallel(1, true)```.
So, you should use ```nn.DataParallel(1, true)```.
